Fix ubl_template picking, always return DeliveredQuantity
OCA/edi pull request #1065
Opened 2024-11-14 07:13 UTC by cyrilmanuel

f you look at the other templates, there is no t-if for the DeliveredQuantity, so it will always be there even if the qty = 0

The block for `t-if="line.Mngs_Mng"` can be dropped and then the t-if="t-if="line.IvAusp_LiefMngsWamas_Mng"" in the second block can be removed 

the first one comes from watepq telegram and the second one from auspq telegram. We parse only auspq, so we don't need such condition

2024-11-14 07:34 UTC, jbaudoux approved these changes

2024-11-14 07:36 UTC, jbaudoux requested changes

2024-11-14 07:36 UTC, jbaudoux commented on base_wamas_ubl/lib/wamas/ubl_template/picking.xml
> +		<t t-raw="line.Mngs_Mng or line.IvAusp_LiefMngsWamas_Mng" />
oh, this line needs to move inside the DeliveredQuantity block instead of the other

2024-11-14 08:41 UTC, jbaudoux approved these changes

2024-11-15 06:25 UTC, santostelmo approved these changes

2024-11-15 06:50 UTC, Ricardoalso approved these changes

2024-11-15 06:50 UTC, Ricardoalso commented on base_wamas_ubl/lib/wamas/ubl_template/picking.xml
> +            t-if="line.Mngs_Mng or line.Mngs_Mng == 0"
Not a big issue but this if condition and the one below are kind of useless as they will always be True

2024-11-15 07:12 UTC, santostelmo commented on base_wamas_ubl/lib/wamas/ubl_template/picking.xml
> +            t-if="line.Mngs_Mng or line.Mngs_Mng == 0"
I agree, this t-if could be dropped

2024-11-15 12:25 UTC, jbaudoux commented on base_wamas_ubl/lib/wamas/ubl_template/picking.xml
> +            t-if="line.Mngs_Mng or line.Mngs_Mng == 0"
@cyrilmanuel Why you went back from your initial change where you kept only one `DeliveredQuantity` block? It looked correct. It doesn't make sense to have twice the block and it should be always there, so `t-if` should be dropped

2024-11-15 15:58 UTC, cyrilmanuel commented on base_wamas_ubl/lib/wamas/ubl_template/picking.xml
> +            t-if="line.Mngs_Mng or line.Mngs_Mng == 0"
Hi, with only one block its not working the block contain only value set to none. Same for the if.

2024-11-18 14:00 UTC, simahawk commented on base_wamas_ubl/lib/wamas/ubl_template/picking.xml
> +            t-if="line.Mngs_Mng or line.Mngs_Mng == 0"
I agree that the comparison to zero seem useless

2024-11-19 08:46 UTC, jbaudoux commented on base_wamas_ubl/lib/wamas/ubl_template/picking.xml
> +            t-if="line.Mngs_Mng or line.Mngs_Mng == 0"
Repeating the block with a condition is useless as the block is mandatory and can be there only once. i'm convinced it should be just a matter of expressing properly the value extraction inside the unique block

2024-11-19 13:19 UTC, cyrilmanuel commented on base_wamas_ubl/lib/wamas/ubl_template/picking.xml
> +            t-if="line.Mngs_Mng or line.Mngs_Mng == 0"
@jbaudoux  @simahawk  i have made the modification could you explain me what i've made wrong ?

2024-11-19 15:24 UTC, jbaudoux requested changes
You will also need to remove the blank line in `wamas/tests/samples/WAMAS2UBL-SAMPLE_AUSKQ_WATEKQ_WATEPQ-DESPATCH_ADVICE.xml`

```
  		</cbc:DeliveredQuantity>
- 		
  		<cac:OrderLineReference>
```

2024-11-19 15:24 UTC, jbaudoux commented on base_wamas_ubl/lib/wamas/ubl_template/picking.xml
> +		<t t-raw="line.Mngs_Mng or line.IvAusp_LiefMngsWamas_Mng" />
If the expression is wrong, it will silently return "None". You need to check if the attribute is part of the object before accessing it

```suggestion
        <t t-raw="hasattr(line,'Mngs_Mng') and line.Mngs_Mng or (hasattr(line, 'IvAusp_LiefMngsWamas_Mng') and line.IvAusp_LiefMngsWamas_Mng) or 0.0" />
```

2024-11-19 15:25 UTC, jbaudoux commented on base_wamas_ubl/lib/wamas/ubl_template/picking.xml
> +            t-if="line.Mngs_Mng or line.Mngs_Mng == 0"
sure, see below

2024-11-20 08:07 UTC, jbaudoux approved these changes
Yes, like that :)

2024-12-06 13:43 UTC, jbaudoux commented
/ocabot merge patch

2024-12-06 13:48 UTC, merged