[14.0][IMP] product_import: Import products asynchronously
OCA/edi pull request #1076
Opened 2024-11-29 09:05 UTC by florentx

2024-12-03 12:21 UTC, simahawk requested changes

2024-12-03 12:21 UTC, simahawk commented on product_import/wizard/product_import.py
> +        product = self.create_update_product(parsed_product, messgs, seller_id)
Sounds weird to have a public method called by the private one. It should be the other way around.
And why passing empty `messgs`?

2024-12-03 12:21 UTC, simahawk commented on product_import/tests/test_product_import.py
> +        products = (
existing = ...search()
new = ...search() - existing

2024-12-03 12:21 UTC, simahawk commented on product_import/wizard/product_import.py
>          self._bdimport.post_create_or_update(catalogue, seller, doc_filename=filename)
Is it correct to call the post update here?
Also, now you have 3 methods to the import... why do you need them all?

2024-12-03 16:53 UTC, florentx commented on product_import/wizard/product_import.py
>          self._bdimport.post_create_or_update(catalogue, seller, doc_filename=filename)
Refactored.

2024-12-04 09:48 UTC, twalter-c2c approved these changes
LGTM

2024-12-10 13:50 UTC, simahawk commented on product_import/__manifest__.py
> +        "queue_job",
I've thought again about this... We should remove this dependency IMO.
In the simplest case we won't need it, in the more complex case we'll probably use the framework. Then, we can leverage the framework to the split. 
Additionally, there's now a new feature in queue_job which is called `split` and allows to.... split items in batches.
See https://github.com/OCA/queue/pull/658

2024-12-10 13:50 UTC, simahawk commented on product_import/wizard/product_import.py
> +            wiz.with_delay()._create_update_products(products, seller.id)
here I would simply call `wiz.create_update_products` that will call `_create_update_products` which can be overridden or you can rely on https://github.com/OCA/queue/blob/16.0/queue_job/models/base.py#L145

2025-01-28 10:56 UTC, twalter-c2c approved these changes
LGTM

2026-01-04 12:36 UTC, closed without merging