[10.0] Update invoice2data library reference link
OCA/edi pull request #139
Opened 2019-10-07 18:09 UTC by matteotrubini

From https://github.com/m3nu/invoice2data to https://github.com/invoice-x/invoice2data

2019-10-07 21:43 UTC, rvalyi approved these changes

2019-10-08 12:26 UTC, alexis-via requested changes

2019-10-08 12:26 UTC, alexis-via commented on account_invoice_import_invoice2data/README.rst
> +For the PDF invoice of your supplier that don't have an embedded XML file, you will have to create a `template file <https://github.com/invoice-x/invoice2data/blob/master/invoice2data/templates>`_ in
The link is now this one: https://github.com/invoice-x/invoice2data/tree/master/src/invoice2data/extract/templates

2019-10-08 12:26 UTC, alexis-via commented on account_invoice_import_invoice2data/README.rst
> +* Take `Free SAS template file <https://github.com/invoice-x/invoice2data/blob/master/invoice2data/templates/fr/fr.free.adsl-fiber.yml>`_ as an example. You will find a sample PDF invoice for this su
The link is now this one: https://github.com/invoice-x/invoice2data/blob/master/src/invoice2data/extract/templates/fr/fr.free.adsl-fiber.yml

2019-10-08 15:09 UTC, alexis-via approved these changes

2019-10-08 15:09 UTC, merged