[13.0][MIG] base_ubl
OCA/edi pull request #154
Opened 2019-12-13 10:53 UTC by astirpe

Depends on:

- [ ] uom_unece https://github.com/OCA/community-data-files/pull/71
- [ ] account_tax_unece https://github.com/OCA/community-data-files/pull/74
- [ ] base_vat_sanitized https://github.com/OCA/partner-contact/pull/821

2019-12-17 10:29 UTC, CasVissers commented
@astirpe 
Also depends on base_vat_sanitized not yet available for v13

2019-12-17 10:34 UTC, astirpe commented
@CasVissers to speed up the approval, you may want to review this: https://github.com/OCA/partner-contact/pull/821
I will fix the dependencies in this PR once one on the two unece modules are merged.

2019-12-17 11:00 UTC, CasVissers-360ERP commented on base_ubl/models/ubl.py
> +            contact_name.text = partner.name
@astirpe When creating an invoice-contact the field name is not mandatory. Therefore the partner of an invoice can be without a name. Maybe we should change this too: parter.name or partner.parent_id.name?

2019-12-17 11:16 UTC, CasVissers-360ERP approved these changes
👍 LGTM, functional test

2019-12-30 07:26 UTC, CasVissers-360ERP approved these changes
Tested and confirmed 👍

2020-03-02 16:02 UTC, alexis-via requested changes
We need to remove the dependency on base_vat_sanitized because this feature is now native in base_vat in v13.

2020-03-03 07:58 UTC, astirpe commented
@alexis-via done. Thanks!

2020-03-03 09:14 UTC, alexis-via approved these changes

2020-03-03 09:14 UTC, merged