IMP purch_order: allow to using xml with no pdf and hook to customize xml
OCA/edi pull request #178
Opened 2020-03-28 16:29 UTC by bealdav

UBL is not always used with pdf but also with EDI plateform with xml only

Here some function split to serve multi usage

Please @astirpe @lmignon @SimoRubi @alexis-via could you have a look here.

Thanks a lot for your contribution

2020-03-30 07:02 UTC, astirpe approved these changes
LGTM

2020-03-30 07:32 UTC, astirpe requested changes

2020-03-30 07:32 UTC, astirpe commented on purchase_order_ubl/models/purchase.py
> +                xml_string, self.document_name(doc_type), version=version)
Here you invoke `document_name` but method name is `get_document_name`

2020-03-30 07:32 UTC, astirpe commented on purchase_order_ubl/models/purchase.py
> +    def guess_ubl_doc_type(self):
Could you rename this method into `get_ubl_purchase_order_doc_type`? To make it consistent with https://github.com/OCA/edi/commit/4332084640b1933e6cf3742d4d697f2d2e8839a2#diff-54f706660be5cb2e069c3ec2c09f6dd9R214

2020-03-30 07:36 UTC, astirpe commented on purchase_order_ubl/models/purchase.py
> +    def get_document_name(self, doc_type):
```suggestion
    def get_document_name(self, doc_type):
        document = False
```

2020-03-30 13:11 UTC, astirpe approved these changes

2020-03-30 13:26 UTC, bealdav commented
Thanks a lot @astirpe

2020-03-31 13:44 UTC, florian-dacosta approved these changes
LGTM

2020-03-31 13:48 UTC, bguillot approved these changes
LGTM

2020-04-01 09:57 UTC, bealdav commented
Hi @alexis-via you're the man of the situation here. Thanks

2020-04-03 09:21 UTC, merged

2020-04-03 09:33 UTC, bealdav commented
Thanks a lot Alexis