[10.0][IMP] add despatch advice import
OCA/edi pull request #280
Opened 2020-12-09 08:48 UTC by lmarion-source

includes #244

2020-12-09 17:57 UTC, bealdav commented
Hi @lmarion-source and @lmignon 

Thanks to share your work on despatch-advice as a new UBL flow. Did you considered to put this flow in an other module than purchase_order_import ? Maybe a module `despatch_advice`.

If yes, I think backport and forward port could be made simple.

What do you think ?

2020-12-17 11:21 UTC, bealdav commented
perfect

2021-02-03 07:07 UTC, bealdav approved these changes

2021-02-15 17:01 UTC, lmignon commented
@lmarion-source Can you fix pytlint PLZ https://travis-ci.com/github/OCA/edi/jobs/482189881#L326
Thanks!

2021-03-12 11:17 UTC, lmignon commented on despatch_advice_import/wizard/despatch_advice_import.py
>          for line_id, line_info in lines_by_id.iteritems():
@lmarion-source You must avoid to search the lines and orders line by line....
```
lines = self.env["purchase.order.line"].browse(lines_by_id.keys())
```

2021-03-12 11:21 UTC, lmignon requested changes

2021-03-12 11:21 UTC, lmignon commented on despatch_advice_import/wizard/despatch_advice_import.py
> +            order = self.env["purchase.order"].search([("name", "=", line_info["ref"])])
The order is available on the line `order = line.order_id`. Yous should only check:
 * if the order ref is provided, the line.order_id.ref must == order_ref
 * if no order ref provided: line.order_id.name == po_name

2021-04-07 20:08 UTC, bealdav commented on despatch_advice_import_ubl/README.rst
> +Import Despatch Advice files
In fact there 2 workflow with despatch:

1. yours: your receive file about goods that'll receive soon
2. other flow: you define a delivery order for your customer (picking out is created at sale confirmation) and your warehouse site/manager send you a file to indicate which lots are really sent, then have to match with an existing picking

Probably interesting to define here that you only implements the first one. Thanks

2021-04-07 20:09 UTC, bealdav commented on despatch_advice_import_ubl/README.rst
> +Import Despatch Advice files
I have to implement the last in v12, for information

2021-04-07 20:17 UTC, bealdav commented on despatch_advice_import_ubl/README.rst
> +Import Despatch Advice files
Also a despatch, couldn't be linked to an order (sale or purchase) even if UBL require it.
In that case, we only deal with picking, for example between warehouses

2021-04-08 08:25 UTC, bealdav commented on despatch_advice_import_ubl/README.rst
> +Import Despatch Advice files
Please @lmignon @lmarion-source are you OK with the different possible use cases ? Sure I don't want you implement them here. Just I would know if I'm not in error functionally speaking. Thanks

2022-06-12 12:23 UTC, closed without merging