[MIG] partner_identification_import: Migration to 14.0
OCA/edi pull request #332
Opened 2021-02-27 09:46 UTC by dzungtran89

Dependencies:
- partner_identification: https://github.com/OCA/partner-contact/pull/1058
- base_business_document_import: https://github.com/OCA/edi/pull/301

2021-08-03 09:28 UTC, sebalix requested changes
LG, small change requested

2021-08-03 09:28 UTC, sebalix commented on partner_identification_import/models/business_document_import.py
> +                    .join(unmatched)
```suggestion
                    .format(_("or\n").join(unmatched))
```

2021-08-03 09:28 UTC, sebalix commented on test-requirements.txt
> +odoo14-addon-partner-identification @git+https://github.com/phuctranerp/partner-contact@14.0-mig-partner_identification#subdirectory=setup/partner_identification
To remove now that dependencies are merged

2021-08-03 10:56 UTC, dzungtran89 commented on partner_identification_import/models/business_document_import.py
> +                    .join(unmatched)
ok, thx

2021-08-03 11:56 UTC, simahawk approved these changes
@sebalix fine for you?

2021-08-05 07:30 UTC, sebalix approved these changes

2021-08-05 07:40 UTC, simahawk commented
oh I missed 3 commits that should be squashed. @dzungtran89 could you do it? Otherwise I do it.

2021-08-05 08:20 UTC, dzungtran89 commented
Hi @simahawk , I'll do it

2021-08-06 09:11 UTC, simahawk commented
/ocabot merge nobump

2021-08-06 09:23 UTC, merged

2021-11-04 11:55 UTC, simahawk commented on partner_identification_import/models/business_document_import.py
> +                    .format_("or\n")
there's typo here. I'll fix it while fwd porting other changes.