[14.0] [mig] sale_order_ubl
OCA/edi pull request #356
Opened 2021-03-31 10:52 UTC by fshah-initos

2021-04-07 14:35 UTC, rconjour requested changes

2021-04-07 14:35 UTC, rconjour commented on sale_order_ubl/models/report.py
> +    def render_qweb_pdf(self, res_ids=None, data=None):
If i'm right, the upstream name of this element is `_render_qweb_pdf`

2021-04-07 14:35 UTC, rconjour commented on sale_order_ubl/tests/test_ubl_generate.py
> +                ).render_qweb_pdf(order.ids)[0]
This should also be`_render_qweb_pdf`

2021-04-09 06:43 UTC, rconjour approved these changes

2021-04-09 07:04 UTC, StefanRijnhart approved these changes
Thanks!

/ocabot merge nobump

2021-04-09 07:40 UTC, StefanRijnhart commented
Bot? Bot? Where are you bot?

/ocabot merge nobump

2021-04-09 08:00 UTC, merged