[13.0][ADD] edi_voxel_stock_picking_secondary_unit: new module
OCA/edi pull request #360
Opened 2021-04-05 16:02 UTC by ernestotejeda

Cc @Tecnativa TT28726

This module extends the functionality of 'Voxel stock picking' module to match secondary units of measure instead of standard units of measure during the stock picking sending process.

Note: I included the commit of the PR of the edi_voxel_secondary_unit (https://github.com/OCA/edi/pull/357) module until it is merged

2021-04-06 06:19 UTC, sergio-teruel approved these changes

2021-04-06 06:21 UTC, CarlosRoca13 approved these changes
As I said in the other module, can you separate in two diferent commits the changes of edi_voxel_stock_picking from the addition of the new module??

2021-04-06 06:26 UTC, pedrobaeza commented
In fact, both are including #357 as extra commit for having the CI green. You should review that one, got merged, and then this PR should be rebased.

2021-04-06 13:47 UTC, ernestotejeda commented
> As I said in the other module, can you separate in two diferent commits the changes of edi_voxel_stock_picking from the addition of the new module??

@CarlosRoca13 changes done.

2021-04-06 15:56 UTC, pedrobaeza requested changes

2021-04-06 15:56 UTC, pedrobaeza commented on edi_voxel_stock_picking/reports/report_voxel_picking.py
> +        qty, mu = self._get_qty_mu(line)
Don't add  new method, but override existing one `_get_product_data`

2021-04-06 15:56 UTC, pedrobaeza commented on edi_voxel_stock_picking/tests/test_voxel_stock_picking.py
>      def test_get_voxel_filename(self):
Same problem of test executed twice.

2021-04-06 15:56 UTC, pedrobaeza commented on edi_voxel_stock_picking_secondary_unit/README.rst
> +Module name
This is not correct

2021-04-06 15:56 UTC, pedrobaeza commented on edi_voxel_stock_picking_secondary_unit/__manifest__.py
> +    "summary": "Map Voxel UoM to Stock Pickking Secondary UoM and Use Them",
```suggestion
    "summary": "Export Secondary UoMs Voxel Code in picking Voxel documents",
```

2021-04-06 15:56 UTC, pedrobaeza commented on edi_voxel_stock_picking_secondary_unit/reports/report_voxel_picking.py
> +    def _get_qty_mu(self, line):
The already commented about which method to override.

2021-04-07 21:53 UTC, ernestotejeda commented
@pedrobaeza changes done

2021-04-19 17:58 UTC, pedrobaeza approved these changes

2021-04-19 17:58 UTC, pedrobaeza commented
/ocabot merge nobump

2021-04-19 18:29 UTC, merged