[14.0] [mig] edi_storage_oca
OCA/edi pull request #372
Opened 2021-05-06 06:27 UTC by fshah-initos

2021-05-06 06:36 UTC, simahawk requested changes
edi_oca is missing: mention it in the description and please review https://github.com/OCA/edi/pull/371 to get it merged quickly

2021-05-06 06:36 UTC, simahawk commented on edi_storage_oca/readme/CONTRIBUTORS.rst
> +* Foram Shah <foram.shah@initos.com>
@fshah-initos you can add yourself if here if you provide something more than a bare migration.
TIP: test coverage is very welcomed :wink:

2021-05-10 07:55 UTC, etobella commented
@fshah-initos Rebase to have edi_oca installed here pleasae :wink:

2021-05-10 14:42 UTC, etobella commented
Travis is green finally :smile: However, a rebase would be great in order to have the runbot too

2021-05-13 11:12 UTC, fshah-initos commented
All the checks are passed now it is possible to merge the PR.

2021-05-13 11:34 UTC, etobella commented
Can you provide better tests please as commented by @simahawk

2021-05-13 14:38 UTC, simahawk commented
> Can you provide better tests please? as commented by @simahawk

Just to be clear: I didn't ask for tests. I just suggested that if you want to figure as contributor you could add tests (or anything else that adds value). BTW this is a well known practice in the OCA. I was just reminding it here :wink:

2021-05-13 14:39 UTC, simahawk commented
> Can you provide better tests please? as commented by @simahawk

Just to be clear: I didn't ask for tests. I just suggested that if you want to figure as contributor you could add tests (or anything else that adds value). BTW this is a well known practice in the OCA. I was just reminding it here :wink:

2021-05-13 14:39 UTC, simahawk commented
Ops. I pushed the wrong btn, sorry :sweat_smile:

2021-05-27 12:50 UTC, fshah-initos commented
Is it possible to merge this PR?

2021-05-27 13:06 UTC, simahawk approved these changes

2021-05-27 13:06 UTC, simahawk commented
/ocabot merge nobump

2021-05-27 13:16 UTC, merged