[MIG] edi: fix external identifier
OCA/edi pull request #480
Opened 2021-11-08 10:48 UTC by olgamarcocb

Standard Migration #473

2021-11-08 11:00 UTC, simahawk requested changes
you should cherry-pick @etobella commit (or use format-patch)

2021-11-09 09:19 UTC, etobella approved these changes

2021-11-09 11:04 UTC, simahawk approved these changes

2021-11-09 11:04 UTC, simahawk commented
/ocabot merge minor

2021-11-09 13:06 UTC, merged