[FIX] requirements.txt: Removed PyPDF2 library
OCA/edi pull request #665
Opened 2022-09-14 19:34 UTC by lescobarvx

In the requirement file of odoo/odoo the library is pinned to version 1.26.0
    (https://github.com/odoo/odoo/commit/021de21e8cdcf35276c945d8070d04435fa1a19c),
    if library is unpinned, it is forced to install the current version, which
    generates the following error when running odoo:

    AttributeError: module 'PyPDF2' has no attribute 'filters'

2022-09-14 19:58 UTC, luisg123v requested changes
Since requirements are built up from manifest's requirements, you need to remove dependencies also from there.

In addition, the `requests` requirement is in the same situation.

CC @suniagajose

2022-09-15 04:45 UTC, suniagajose commented
> Since requirements are built up from manifest's requirements, you need to remove dependencies also from there.
> 
> In addition, the `requests` requirement is in the same situation.
> 
> CC @suniagajose

Complementing your comment @luisg123v 

https://github.com/odoo/odoo/blob/14.0/requirements.txt#L38

2022-09-15 15:05 UTC, etobella commented
requirements.txt is generated automatically from manifests. You need to remove the library from external_dependancies key on the manifest

2022-09-15 15:05 UTC, etobella commented
Or pin it there to the expected value

2022-09-15 17:23 UTC, luisg123v requested changes
Hi @lescobarvx,

- You need to perform a commit per module. That's because, when modules are migrated, history is brought taking commits related to that module. So, if you leave only only commit, if both modules are migrated, commit will be duplicated in next version
- Missing removing `requests`, that is in the module `account_invoice_download_ovh`

2022-09-15 18:45 UTC, luisg123v approved these changes
LGTM :+1: 

@moylop260 could you review, please?

2022-09-16 00:41 UTC, moylop260 approved these changes
👍

2022-09-16 00:43 UTC, moylop260 commented
The CI is even green and the PR is already approved so...

2022-09-16 00:43 UTC, moylop260 commented
/ocabot merge minor

2022-09-16 00:52 UTC, merged