[16.0][MIG] account_invoice_import_ubl
OCA/edi pull request #740
Opened 2023-03-24 14:02 UTC by alexis-via

Requires https://github.com/OCA/edi/pull/725
I'll publish account_invoice_import to v16 later on.

2023-04-17 05:50 UTC, acsonefho commented
@alexis-via thank you for this PR :)
Do you already know when you'll open a PR for `account_invoice_import` ?
Thanks!

2023-05-12 10:06 UTC, acsonefho requested changes

2023-05-12 10:06 UTC, acsonefho commented on account_invoice_import_ubl/wizard/account_invoice_import.py
> +        self.get_currency_helper(res)
Where does it come from ?

2023-06-30 10:42 UTC, tarteo commented
This functionality is already in core odoo (account_edi_ubl_cii)

2023-12-03 12:20 UTC, closed without merging

2025-11-04 16:46 UTC, alexis-via commented
For some strange reasons, I can't reopen this PR. So I'll create a new one.