12.0 mig account e invoice generate
OCA/edi pull request #83
Opened 2019-01-10 13:58 UTC by joshuajan

2019-01-10 15:18 UTC, pedrobaeza commented
Can you please see Travis problem and squash your migration commits into one (as they are not very meaningful)?

2019-01-11 12:28 UTC, astirpe commented
Please rebase to fix the travis

2019-01-14 07:47 UTC, joshuajan commented
Dear all, I have rebase and make all change into one commit.

2019-01-14 08:05 UTC, astirpe approved these changes
Thanks!

2019-01-14 08:12 UTC, pedrobaeza requested changes
It would be great that you use the README by fragments system: https://github.com/OCA/maintainer-tools/#readme-generator

2019-01-14 08:12 UTC, pedrobaeza commented on account_e-invoice_generate/__manifest__.py
> +              'Shine IT<contact@openerp.cn>, '
Changes you have made for migrating the module doesn't grant you co-authorship. Please remove this.

2019-01-14 08:14 UTC, pedrobaeza commented
In fact, README by fragment is already used. You have to update that fragments instead for contributors part, and run the utility (or let the bot to run it after the merge, but at least the first step).

2019-01-14 16:07 UTC, joshuajan commented
Dear @pedrobaeza  Thanks for your reply. I have update fragments.

2019-01-16 17:52 UTC, pedrobaeza approved these changes

2019-01-16 17:52 UTC, merged