[IMP] base_business_document_import: Improve Coverage
OCA/edi pull request #845
Opened 2023-11-01 21:15 UTC by bosd

2023-11-27 10:25 UTC, bofiltd approved these changes
LGTM

2023-11-28 08:58 UTC, Dranyel-Bosd approved these changes
LGTM :+1:

2024-01-13 14:53 UTC, bosd commented
@alexis-via Can you merge? :pray:

2024-02-04 13:21 UTC, bosd commented
@simahawk Can you please merge?

2024-03-13 12:04 UTC, bosd commented
@alexis-via Can you merge?

2024-03-13 12:15 UTC, simahawk commented on base_business_document_import/tests/test_business_document_import.py
> +_logger = logging.getLogger("odoo.tests.test_module_operations")
I don't understand the usage of this logger

2024-03-13 12:16 UTC, simahawk commented
> @simahawk Can you please merge?

Sorry, I have a huge pile of pings/PRs to review... I missed this one.
Don't hesitate to ping me more than once if you get stuck :wink:

2024-07-15 05:38 UTC, bosd commented on base_business_document_import/tests/test_business_document_import.py
> +_logger = logging.getLogger("odoo.tests.test_module_operations")
@simahawk I reverted it. Is it ok now?

2024-07-15 07:13 UTC, bosd commented
It is ready now, bot please remove the stale label.

2024-07-30 16:59 UTC, bosd commented
> Don't hesitate to ping me more than once if you get stuck 😉

@simahawk This one is stuck. Can you please merge?

2024-09-30 13:50 UTC, bosd commented
It has the approved label.. can we get a merge?

2025-02-02 22:15 UTC, bosd commented
@simahawk :eyes: ? :pray:

2025-06-15 15:32 UTC, simahawk requested changes

2025-06-15 15:32 UTC, simahawk commented on base_business_document_import/tests/test_business_document_import.py
> +            logger.info("Exception catched.")
this is not the way to test exceptions. It should use `self.assertRaises` or even better `assertRaisesRegex`

2025-11-23 12:31 UTC, closed without merging