[16.0][ADD] account_invoice_edifact
OCA/edi pull request #854
Opened 2023-11-07 03:17 UTC by thienvh332

This new module will support generate customer invoice with EDIFACT/D96A format.

Depends on:

- https://github.com/OCA/edi/pull/853

2023-11-16 15:01 UTC, simahawk requested changes

2023-11-16 15:01 UTC, simahawk commented on account_invoice_edifact/models/account_move.py
> +    def edifact_export_invoice(self):
It's just generating data, not really exporting

```suggestion
    def edifact_invoice_generate_data(self):
```

2023-11-16 15:01 UTC, simahawk commented on account_invoice_edifact/models/account_move.py
> +        recipient = id_number.search([("partner_id", "=", self.partner_id.id)])
```suggestion
        sender = id_number.search(
            [("partner_id", "=", self.invoice_user_id.partner_id.id)],
            limit=1
        )
        recipient = id_number.search([("partner_id", "=", self.partner_id.id)], limit=1)
```

2023-11-16 15:01 UTC, simahawk commented on account_invoice_edifact/models/account_move.py
> +    def _edifact_export_invoice_interchange(self):
```suggestion
    def _edifact_invoice_get_interchange(self):
```

2023-11-16 15:01 UTC, simahawk commented on account_invoice_edifact/models/account_move.py
> +    def _edifact_export_invoice_header(self):
```suggestion
    def _edifact_invoice_get_header(self):
```

2023-11-16 15:01 UTC, simahawk commented on account_invoice_edifact/models/account_move.py
> +        shipper_id_number = id_number.search([("partner_id", "=", shipper.id)])
```suggestion
        seller_id_number = id_number.search([("partner_id", "=", seller.id)], limit=1)

        shipper = self.partner_shipping_id
        shipper_id_number = id_number.search([("partner_id", "=", shipper.id)], limit=1)
```

2023-11-16 15:01 UTC, simahawk commented on account_invoice_edifact/models/account_move.py
> +        payment_term = min(self.invoice_payment_term_id.line_ids, default=None)
I'm no sure to understand this usage of `min` here

2023-11-16 15:01 UTC, simahawk commented on account_invoice_edifact/models/account_move.py
> +                            for picking in order.picking_ids
shouldn't you filter on the delivery only?

2023-11-16 15:01 UTC, simahawk commented on account_invoice_edifact/models/account_move.py
> +            (
maybe these parts can be split to their own methods? Eg: `_edifact_invoice_get_[buyer|seller|you-name-it]`.

2023-11-16 15:01 UTC, simahawk commented on account_invoice_edifact/models/account_move.py
> +    def _edifact_export_invoice_product(self):
```suggestion
    def _edifact_invoice_get_product(self):
```

2023-11-16 15:01 UTC, simahawk commented on account_invoice_edifact/models/account_move.py
> +        self.ensure_one()
As these methods are a private api meant to be used inside the main one to me is useless to keep ensuring that you get one record only... not a blocker tho.

2023-11-16 15:01 UTC, simahawk commented on account_invoice_edifact/models/account_move.py
> +            if line.display_type == "product":
```suggestion
            if line.display_type != "product":
                continue
```
and you save a looooot of indentation in the rest of the method

2023-11-16 15:01 UTC, simahawk commented on account_invoice_edifact/tests/test_account_move.py
> +        super().setUpClass()
pls disable mail tracking globally

2023-11-17 03:48 UTC, thienvh332 commented on account_invoice_edifact/models/account_move.py
> +                            for picking in order.picking_ids
On the document they sent there was no DTM+35, so I relied on the EDIFACT convention. In EDIFACT DTM+35 is Delivery date/time, actual. So I decided to get picking.date_done. If you have any suggestions I will fix it.

2023-11-17 09:10 UTC, thienvh332 commented on account_invoice_edifact/tests/test_account_move.py
> +        super().setUpClass()
Thanks @simahawk , I updated

2024-02-01 16:09 UTC, simahawk approved these changes

2024-02-01 16:10 UTC, simahawk commented
/ocabot merge nobump

2024-02-01 16:16 UTC, merged