[14.0][ADD] edi_product_import
OCA/edi pull request #882
Opened 2023-12-01 10:18 UTC by florentx

New glue add-on `edi_product_import`

(initial PR #760)

2023-12-01 12:30 UTC, simahawk commented
I'd say this module should go to https://github.com/OCA/edi-framework and be based on https://github.com/OCA/edi-framework/pull/43 (to be backported to 14.0) so that you can also see exchanges linked to the product.

2023-12-04 09:44 UTC, mmequignon approved these changes
Ok with that, though I don't know about @simahawk comment

2024-01-10 22:15 UTC, bofiltd approved these changes
LGTM

2024-05-04 02:37 UTC, bosd approved these changes

2024-05-16 05:37 UTC, bofiltd commented
Any update on this?

2024-09-25 18:27 UTC, bosd commented
> Ok with that, though I don't know about @simahawk comment

@simahawk Can you elaborate?
Should we merge it in this repo?

2025-01-28 08:46 UTC, simahawk requested changes
my comment remain valid

2025-01-28 09:44 UTC, florentx commented
For Odoo 14, it would add some burden to depend on `edi_product_oca` because:
 - add-on `edi_oca` is still in `OCA/edi` repositiory and it will probably stay there (14.0 is old/stable enough)
 - add-on `edi_product_oca` does not exist for 14.0, neither in `OCA/edi-framework` and neither in `OCA/edi`
 - even if porting `edi_product_oca` to 14.0 seems doable, it seems it will just make the dependencies more complicated for not much benefits

2025-01-28 10:45 UTC, simahawk commented
Fair enough. I definitely see benefits in depending on it, in general... Yet, as for 14 let's go this way and simply add a TODO for migration.

2025-07-06 12:33 UTC, closed without merging