[12.0] mig account_invoice_import_ubl
OCA/edi pull request #93
Opened 2019-03-09 21:46 UTC by rubdos

Depends on:
- [ ] #85 -- I will rebase on that PR (or on 12.0 when it'd be merged)

Currently this is the initial `git format-patch --keep-subject --stdout origin/12.0..origin/11.0 -- $MODULE | git am -3 --keep`.

2019-03-14 08:55 UTC, astirpe requested changes

2019-03-14 08:55 UTC, astirpe commented on account_invoice_import/__manifest__.py
> +        'account_payment_partner',
I think this dependency is not needed anymore. Could you check?

2019-03-14 08:55 UTC, astirpe commented on account_invoice_import/__manifest__.py
> +    'website': 'http://www.akretion.com',
```suggestion
    'website': 'https://github.com/OCA/edi',
```

2019-03-14 08:55 UTC, astirpe commented on account_invoice_import/wizard/account_invoice_import.py
> +        #           'code': 'GZ250',
```suggestion
        #           'default_code': 'GZ250',
```

2019-03-14 08:55 UTC, astirpe commented on account_invoice_import/wizard/account_invoice_import.py
> +        invoice.message_post(_(
```suggestion
        invoice.message_post(body=_(
```
Otherwise I get an error.

2019-03-14 08:55 UTC, astirpe commented on account_invoice_import/wizard/account_invoice_import.py
> +            invoice.message_post(_(
```suggestion
            invoice.message_post(body=_(
```

2019-03-14 08:55 UTC, astirpe commented on account_invoice_import/views/res_config_settings.xml
> +              <label string='Default Taxes'/>
```suggestion
              <span class="o_form_label">Default Taxes</span>
```

This because in 12.0 the label requires a field.

2019-03-14 08:55 UTC, astirpe commented on account_invoice_import/views/res_config_settings.xml
> +      <xpath expr="//div[@data-key='account_invoicing']" position="inside">
```suggestion
      <xpath expr="//div[@data-key='account']" position="inside">
```

2019-03-14 08:55 UTC, astirpe commented on account_invoice_import/tests/test_invoice_import.py
> +                'name': 'ASUSTeK',
```suggestion
                'name': 'Wood Corner',
```

2019-03-14 08:55 UTC, astirpe commented on account_invoice_import/tests/test_invoice_import.py
> +                'product': {'code': 'AII-TEST-PRODUCT'},
```suggestion
                'product': {'default_code': 'AII-TEST-PRODUCT'},
```

2019-03-14 08:55 UTC, astirpe commented on account_invoice_import/tests/test_invoice_import.py
> +                'name': 'Agrolait',
```suggestion
                'name': 'Deco Addict',
```

2019-03-14 08:55 UTC, astirpe commented on account_invoice_import/tests/test_invoice_import.py
> +                'product': {'code': 'AII-TEST-PRODUCT'},
```suggestion
                'product': {'default_code': 'AII-TEST-PRODUCT'},
```

2019-05-08 02:38 UTC, TheCloneMaster commented
Hi, is this PR still alive?
How could we help?

2019-05-08 06:39 UTC, astirpe commented
@TheCloneMaster this PR depends on https://github.com/OCA/edi/pull/85 that is not yet merged. You may want to review that one first.
@rubdos could you accept the changes I proposed?

2019-12-31 18:57 UTC, mgielissen commented
https://github.com/OCA/edi/pull/85 is merged into 12.0

2020-01-02 17:50 UTC, njeudy commented
how can we help on it ?

2020-01-03 09:34 UTC, astirpe commented
Superseded by #162 due to inactivity

2020-01-03 09:34 UTC, closed without merging