[IMP] sale_order_import: push errored lines to chatter and ignore them when importing
OCA/edi pull request #979
Opened 2024-05-29 03:51 UTC by QuocDuong1306

Example:

![image](https://github.com/OCA/edi/assets/127363167/13901c72-ead4-43a5-b085-480bf538b852)

2024-05-29 09:30 UTC, simahawk requested changes
While this is a good improvement I think we need to make one more step: opt in + better formatting.
IMO we should be able to decide if the lines have to be skipped or not especially because we are introducing this on existing instances. We need a flag that is false by default: `skip_error_lines`.

Then I would add a specific template to render instead of creating HTML ourselves and I would render each key properly w/ a list of `label: value`.

Reminder for commit message: always keep in mind that the main msg is a short summary of what you are changing and you should delegate the explanation to the description of the commit.

In this case it should be something like:

```
[imp] sale_order_import: better line error handling

Show errored lines in the chatter and ignore them on demand when importing.
```

2024-06-02 14:34 UTC, QuocDuong1306 commented
Hi @simahawk , I updated the code, commit's message, and PR's description as well. Could you have a look?

2024-06-11 05:14 UTC, santostelmo approved these changes

2024-06-11 05:59 UTC, simahawk requested changes

2024-06-11 05:59 UTC, simahawk commented on sale_order_import/static/src/scss/error_lines_chatter_msg.scss
> +div.error-line-message {
we don't need these styles IMO if you use Bootstrap built-in utils

2024-06-11 05:59 UTC, simahawk commented on sale_order_import/templates/error_lines_chatter_msg.xml
> +            <div class="error-line-message">
```suggestion
            <div class="alert alert-warning" role="alert">
```
please look for examples among the many in odoo code

2024-06-11 05:59 UTC, simahawk commented on sale_order_import/templates/error_lines_chatter_msg.xml
> +        <t t-foreach="lines" t-as="line" t-key="line_index">
What is `t-key`? Inside a loop you always have `line_index`.
https://www.odoo.com/documentation/17.0/developer/reference/frontend/qweb.html#loops

2024-06-11 05:59 UTC, simahawk commented on sale_order_import/templates/error_lines_chatter_msg.xml
> +                <span>
use a P instead of a span + br

2024-06-11 05:59 UTC, simahawk commented on sale_order_import/templates/error_lines_chatter_msg.xml
> +    <template id="template_skip_error_lines_message">
```suggestion
    <template id="skip_error_lines_message">
```
this is a template for sure

2024-07-06 08:58 UTC, QuocDuong1306 commented
Thank @simahawk for your suggestions, I added the fixup commit

I am not sure which one you prefer then? Could you please have a look and give me your opinion?

![image](https://github.com/OCA/edi/assets/127363167/0a5ce9ee-7caa-46a5-a658-c9cc260065b6)
And 
![image](https://github.com/OCA/edi/assets/127363167/ccd9db57-31c6-43f5-9120-870504d6fa91)

2024-12-10 13:37 UTC, simahawk commented
> Thank @simahawk for your suggestions, I added the fixup commit
> 
> I am not sure which one you prefer then? Could you please have a look and give me your opinion?
> 
> ![image](https://private-user-images.githubusercontent.com/127363167/346263527-0a5ce9ee-7caa-46a5-a658-c9cc260065b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MzgwMzksIm5iZiI6MTczMzgzNzczOSwicGF0aCI6Ii8xMjczNjMxNjcvMzQ2MjYzNTI3LTBhNWNlOWVlLTdjYWEtNDZhNS1hNjU4LWM5Y2MyNjAwNjViNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxMzM1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWE2OWE0MzgwNzc0NjIxZGRhM2U2MjFhMzE0MDgyZmJkYmZhOWFjZjYxNWNhMjY5OWYyNDViNGM5NmEzYjA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.b-_VAxTnZO6lstoCjTySX5z1U9hTvfErQr-7BJjloVo) And ![image](https://private-user-images.githubusercontent.com/127363167/346263536-ccd9db57-31c6-43f5-9120-870504d6fa91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MzgwMzksIm5iZiI6MTczMzgzNzczOSwicGF0aCI6Ii8xMjczNjMxNjcvMzQ2MjYzNTM2LWNjZDlkYjU3LTMxYzYtNDNmNS05MTIwLTg3MDUwNGQ2ZmE5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxMzM1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MzVkNGRkMGFiMTMwM2FmNjBlMTEzMDFhNTFjMzJiZGY0OTdmOTZlMGI0ODg4NTdhYTQ5NjZmNmRhMzBhNmNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wCKfx3tx3UEfr1wH7oGe0iglxyEI7oIWRXLOrq5iCtc)

The second one is better IMO.

2025-05-25 12:31 UTC, closed without merging

2026-02-11 06:13 UTC, cyrilmanuel commented
@QuocDuong1306  is it possible to fix this one and redo a pr on the camptocamp fork please ?

2026-02-12 05:28 UTC, thienvh332 commented
Superseded by new PR https://github.com/OCA/edi/pull/1293, cc @cyrilmanuel