[IMP] edi_oca: don't consider exchange records if jobs have been created
OCA/edi pull request #996
Opened 2024-06-14 10:34 UTC by MiquelRForgeFlow

If two `_check_output_exchange_sync` are called consecutively, one after the other, maybe due to `_execute_next_action` method, the following error happens:
![Selection_3459](https://github.com/OCA/edi/assets/25005517/acc117ef-b344-44eb-bae3-f85e33d67e11)
Both `_check_output_exchange_sync` calls detect the same exchange records, and both create same jobs. The first batch of jobs will be processed but the second ones will fail due to check of state = "new".

2024-07-17 11:46 UTC, MiquelRForgeFlow commented
@simahawk what's your opinion on this?

2024-07-22 13:50 UTC, simahawk requested changes
We should avoid having this kind of relations w/ jobs.
Please see https://github.com/OCA/queue/pull/573

As for the solution on how to prevent the issue to happen... IMO we should rely on
 the id key https://github.com/OCA/edi-framework/blob/16.0/edi_oca/models/edi_exchange_record.py#L591

And we should leverage the job chaining for inbound records too to speed up processing.

FYI there's a way to find jobs for a record https://github.com/OCA/edi-framework/pull/93

Regarding the error itself: an alternative would be to simply let the job fail gracefully (meaning set it as done). 

BTW I was thinking that we probably need a specific state for when a record is waiting for a job... not sure tho.

2024-07-26 13:31 UTC, MiquelRForgeFlow commented
@simahawk is it acceptable now? It became simpler.

2024-07-29 09:19 UTC, MiquelRForgeFlow commented
@simahawk 

> Regarding the error itself: an alternative would be to simply let the job fail gracefully (meaning set it as done).

Yeah, but silencing possible errors it's bad coding. I prefer avoiding it happening the specific detected ones, and letting the open door to detect other errors.

> BTW I was thinking that we probably need a specific state for when a record is waiting for a job... not sure tho.

A new state between "new" and the others, for example "queued" would be nice, but I am afraid that it's complicated, as we should review all the flows and adapt code. I prefer the boolean solution, it's simpler.

2024-09-04 10:39 UTC, MiquelRForgeFlow commented
@simahawk could you take a look?

2025-01-27 11:55 UTC, MiquelRForgeFlow commented
@simahawk could you take a look? It already has the stale tag...

2025-01-28 08:14 UTC, simahawk commented
@MiquelRForgeFlow I've recently thought about this and I IMO the issue is somewhere else.

If you are using `quick_exec` you should turn off `exchange_file_auto_generate`  and if you do so, the cron will ignore those jobs. 

From my experience the issue comes from there. Nowadays everybody are using `quick_exec` and less and less (if not not at all) relying on the cron to process outgoing records.

I even wonder if it makes sense to keep the cron now that we have  the quick exec + chained the jobs generate/send.

2025-07-06 12:33 UTC, closed without merging